### ISSUE TITLE
sjaracne.exe not found

### ISSUE THREAD

**Issue by fossbert** [jyyulab/SJARACNe#19]
Hi there !
I'm having trouble getting SJARACNe to work. 
Using Ubuntu 18.04 and python3.6(.8) , I first built SJARACNe from source using the commands specified in the instructions. 
After changing permission rights for all scripts in /usr/local/lib/python3.6/dist-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin, I could move forward a little bit. 

Now I'm getting the an 'sjaracne.exe' error thrown at me, see output attached. I cannot find it anywhere and noticed it got removed during development ? 

Any suggestions are much appreciated.

[SJARACNe-Fail.txt](https://github.com/jyyulab/SJARACNe/files/3525456/SJARACNe-Fail.txt)

**Comment by adamdingliang** [comment]
We removed the compiled binary from the repo (not the best practice) and added "build" option to setup.py. You can use "python setup.py build" to build "sjaracne.exe". 

I have added "python setup.py build" to README.md.

**Comment by fossbert** [comment]
It's running now, this seems to have done the job.
Many thanks !

**Comment by adamdingliang** [comment]
Great!
