### ISSUE TITLE
Cannot find probe: XXXX in "tmp/XXX/tf.txt" ... ignored

### ISSUE THREAD

**Issue by SherryDong** [jyyulab/SJARACNe#20]
The error is as follows:

![image](https://user-images.githubusercontent.com/6425734/64302735-4a0f6b00-cfb7-11e9-8242-7794f623cc94.png)

with input file:

[tf_demo.txt](https://github.com/jyyulab/SJARACNe/files/3576925/tf_demo.txt)

This may because the tf.txt is prepared under windows system ?

**Comment by guozihuaa** [comment]
> The error is as follows:
> 
> ![image](https://user-images.githubusercontent.com/6425734/64302735-4a0f6b00-cfb7-11e9-8242-7794f623cc94.png)
> 
> with input file:
> 
> [tf_demo.txt](https://github.com/jyyulab/SJARACNe/files/3576925/tf_demo.txt)
> 
> This may because the tf.txt is prepared under windows system ?

Hi, have you solved this problem. I have tried to convert the tf.txt file as a unix txt format using  dos2unix commond. But i still got this problem.

**Comment by khughitt** [comment]
Same issue here for a completely different probe list. I don't think it has anything to do with the line-encodings of the inputs files.

The issues appears to be related to this part of `main.cpp`, lines 224:225:

```cpp
if (hub.length() == 0 || hub[0] != '_')
    hub = "_" + hub;
```

I'm not sure what the underscore prefix is being used for, but this is where the valid "XX" gene symbols are being converted to "_XX".

**Comment by adamdingliang** [comment]
I do think this is the windows end of line issue. 

The issue relates to the following lines:

`250    for (int i = 0; i < numTFs; i++)
251    {
252       int gid = data.getProbeId(p.tf_list[i]);
253       if (gid == -1)
254          std::cout << "Cannot find probe: " << p.tf_list[i] << " in \""
255                    << p.annotfile << "\" ... ignored." << std::endl;
256       else
257      transfac[gid] = 1;
258    }`
