### ISSUE TITLE
is there a way to run this excellent program in windows10 platform.

### ISSUE THREAD

**Issue by guozihuaa** [jyyulab/SJARACNe#22]
I have installed ANACONDA, python3.6 environemnt and all required packages, but when I run this script, I get error infromations. 

`(python3.6) D:\Users\guozi\Anaconda3\pkgs\SJARACNe-master>sjaracne local -e .\test_data\inputs\BRCA100.exp -g .\test_data\inputs\tf.txt -n 2 -o .\test_data\outputs\finaldata\outdata.txt
INFO:root:test_data\outputs\finaldata\outdata.txt\sjaracne_workflow.yml
INFO:root:exp_file:
  class: File
  path: D:\Users\guozi\Anaconda3\pkgs\SJARACNe-master\test_data\inputs\BRCA100.exp
probe_file:
  class: File
  path: D:\Users\guozi\Anaconda3\pkgs\SJARACNe-master\test_data\inputs\tf.txt
p_value_consensus: 1e-05
p_value_bootstrap: 1e-07
depth: 40
aracne_config_dir:
  class: Directory
  path: D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\sjaracne-0.2.0-py3.6.egg\SJARACNe/config
bootstrap_num: 2
final_out_dir_name: outdata.txt
INFO:root:cwltool --parallel --outdir .\test_data\outputs\finaldata\outdata.txt D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\sjaracne-0.2.0-py3.6.egg\SJARACNe/cwl/sjaracne_workflow.cwl test_data\outputs\finaldata\outdata.txt\sjaracne_workflow.yml
[30mINFO[0m D:\Users\guozi\Anaconda3\envs\python3.6\Scripts\cwltool 1.0.20190618201008
Traceback (most recent call last):
  File "D:\Users\guozi\Anaconda3\envs\python3.6\Scripts\cwltool-script.py", line 11, in <module>
    load_entry_point('cwltool==1.0.20190618201008', 'console_scripts', 'cwltool')()
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\cwltool-1.0.20190618201008-py3.6.egg\cwltool\main.py", line 915, in run
    sys.exit(main(*args, **kwargs))
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\cwltool-1.0.20190618201008-py3.6.egg\cwltool\main.py", line 640, in main
    fetcher_constructor=loadingContext.fetcher_constructor)
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\cwltool-1.0.20190618201008-py3.6.egg\cwltool\load_tool.py", line 89, in resolve_tool_uri
    raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.exceptions.ValidationException: Not found: 'D:UsersguoziAnaconda3envspython3.6libsite-packagessjaracne-0.2.0-py3.6.eggSJARACNe/cwl/sjaracne_workflow.cwl'
Traceback (most recent call last):
  File "D:\Users\guozi\Anaconda3\envs\python3.6\Scripts\sjaracne-script.py", line 11, in <module>
    load_entry_point('SJARACNe==0.2.0', 'console_scripts', 'sjaracne')()
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\sjaracne-0.2.0-py3.6.egg\SJARACNe\sjaracne.py", line 99, in main
    run_shell_command_call(cmd)
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\site-packages\sjaracne-0.2.0-py3.6.egg\SJARACNe\sjaracne.py", line 110, in run_shell_command_call
    subprocess.check_call(cmd_to_exec)
  File "D:\Users\guozi\Anaconda3\envs\python3.6\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cwltool', '--parallel', '--outdir', '.test_dataoutputsfinaldataoutdata.txt', 'D:UsersguoziAnaconda3envspython3.6libsite-packagessjaracne-0.2.0-py3.6.eggSJARACNe/cwl/sjaracne_workflow.cwl', 'test_dataoutputsfinaldataoutdata.txtsjaracne_workflow.yml']' returned non-zero exit status 1.`

it seems that, the cwltool package can not detect the right directory.
I run this in Anacoda prompt. Could you fix this? This program is really important for my research.

**Comment by adamdingliang** [comment]
Hi guozihuaa,

Thanks for your suggestions. cwltool is compatible with Microsoft Windows when Docker is installed: https://github.com/common-workflow-language/cwltool/blob/master/windowsdoc.md. Unfortunately, we don't have docker images built for SJARACNe yet.

As we haven't tested on a Windows platform, the easiest way I can think of for now is to find an unix-based platform to run. An alternative way, which is manual, is to use the Makefile in SJARACNe/SJARACNe directory and build the binary and run each step in SJARACNe/SJARACNe/bin manually.

**Comment by j-andrews7** [comment]
The easiest way to do this is to utilize the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and install/run it from your unix distro of choice. In fact, if you plan to do any bioinformatics on a Windows machine, you'll likely want to familiarize yourself with that setup. It works well.

**Comment by adamdingliang** [comment]
Virtual OS like VMware fusion or VirtualBox under Windows is likely another walkaround.
