### ISSUE TITLE
Add documentation describing sjaracne parameters / suggested settings

### ISSUE THREAD

**Issue by khughitt** [jyyulab/SJARACNe#23]
For example, the `-n` parameter has a default value of "0", but is set to "2" in the README.md examples. The description ("Array measurement noise level") doesn't provide enough information, however, to understand what exactly the parameter is doing, or how to choose an appropriate value, given the type of input data/problem.

Some documentation on [readthedocs](https://readthedocs.org/) would be ideal, but even an expanded explanation on the README.md would be very helpful.

**Comment by adamdingliang** [comment]
Thanks for the suggestion. We don't have the bandwidth to do this right now, but developing formal technical documentation on readthedocs is a direction we are moving towards.
