### ISSUE TITLE
problem when trying to runSJARACNe

### ISSUE THREAD

**Issue by ERIGR** [jyyulab/SJARACNe#25]
Hello,

thank you for you quick answer to my previous question.

Indeed, I was able to run the command sjaracne -h without any error message. However, when trying to run analysis on my own data and on the data presented as example : ```sjaracne local  -e  ~/data/AML/analysis_SJ_ARACNE/BRCA100.exp  -g ~/data/AML/analysis_SJ_ARACNE/tf.txt    -o ~/data/AML/analysis_SJ_ARACNE/SJARACNE_out.final``` . I get the following error message : ```  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
WARNING [job ch_ending_exp] completed permanentFail
WARNING [job ch_ending_probe] completed permanentFail
WARNING [job validate_files] completed permanentFail
ERROR [step ch_ending_exp] Output is missing expected field file:///home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl#ch_ending_exp/out_file
``` . What could be the problem ? Thanks.

**Comment by ERIGR** [comment]
```  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
WARNING [job ch_ending_exp] completed permanentFail
WARNING [job ch_ending_probe] completed permanentFail
WARNING [job validate_files] completed permanentFail
ERROR [step ch_ending_exp] Output is missing expected field file:///home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl#ch_ending_exp/out_file
```. Thanks.

**Comment by adamdingliang** [comment]
Please try to install the newest release SJARACNe 0.2.1. Also check issue #27 . Reopen this issue if the issue persists. Thanks.
