### ISSUE TITLE
command to install and ru SJARACNe (local)

### ISSUE THREAD

**Issue by ERIGR** [jyyulab/SJARACNe#26]
Hi,
sorry to bother you again !  Would it be possible to give all the command (in detail) you used to run SJARACNe locally from the installation of SJARACNe until the launch of the principal command (the command to generate the networks) ? I think that it would facilitate the use of this tool that sounds to me very interesting.
Thanks

**Comment by adamdingliang** [comment]
The commands are platform-dependent. We may help if you post your particular installation errors here. Thanks.
