### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by RavulaPitt** [jyyulab/SJARACNe#27]
Hello,

I am testing SJARACNe on my university HPC in a conda env.

I created a conda env with python 3.6.1, installed dependencies, and installed from source as described on README.

When running SJARCNE I get the following errors as seen in excerpt of output file below. 

1. "PermissionError: [Errno 13] Permission denied" 
2. Output is missing expected field

I saw that there was a closed ticket that also referenced "permission denied" but what was mentioned in that thread was not helpful for me. 

`/ihome/uchandran/raa144/.conda/envs/py36/bin/cwltool 1.0.20190618201008
Resolved '/ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl' to 'file:///ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl'
[workflow ] start
[workflow ] starting step create_seeds
[step create_seeds] start
[workflow ] starting step ch_ending_probe
[step ch_ending_probe] start
[job ch_ending_probe] /scratch/slurm-3928660/b9o4p57e$ ch_line_ending.py \
  -i \
  tf.txt
[workflow ] starting step create_adjmat_names
[step create_adjmat_names] start
[workflow ] starting step ch_ending_exp
[step ch_ending_exp] start

Exception while running job
Traceback (most recent call last):
  File "/ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/site-packages/cwltool/job.py", line 319, in _execute
    monitor_function=monitor_function
  File "/ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/site-packages/cwltool/job.py", line 777, in _job_popen
    cwd=cwd)
  File "/ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

[job ch_ending_probe] completed permanentFail
[workflow ] starting step validate_files
[step validate_files] start
[job ch_ending_exp] /scratch/slurm-3928660/63isl_y2$ ch_line_ending.py \
  -i \
  input.exp
[job validate_files] /scratch/slurm-3928660/ostrz224$ QC_input.py \
  -e \
  input.exp \
  -g \
  tf.txt
[step ch_ending_probe] Output is missing expected field file:///ihome/uchandran/raa144/.conda/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl#ch_ending_probe/out_file
[step ch_ending_probe] completed permanentFail`

**Comment by RavulaPitt** [comment]
Solution found:

https://github.com/jyyulab/SJARACNe/issues/19

As user points out, it is necessary to change the file permissions for all scripts in /usr/local/lib/python3.6/dist-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin.

**Comment by adamdingliang** [comment]
It is kinda hard to replicate this error in my env. We are still trying to figure out the root cause.

**Comment by SamTransformer** [comment]
I encountered the same issue and solved by changing permission, although my mac site package location is different: Users/myname/opt/anaconda3/envs/py374/lib/python3.7/dist-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin/. After entering into this directory in powershell, chmod 755 QC_input.py ch_line_ending.py then everything works fine.

**Comment by adamdingliang** [comment]
Don't see this problem in the new release SJARACNe 0.2.1. Please repen if the problem persists. Thanks.
