### ISSUE TITLE
Possible to control memory / thread usage?

### ISSUE THREAD

**Issue by khughitt** [jyyulab/SJARACNe#3]
Greetings,

I am attempting to run SJARACNe using the default settings on a local workstation with 12 CPUs and 64G memory, for input data with approximate dimensions:

- 58,000 genes x 900 samples
- 1,600 TFs

However, SJARACNe ends up using up all of the memory and freezing the system.

1. Is there any way to predict how much memory will be needed for a given size of data input / maximum partitioning depth?

2. Is there any way to limit the amount of memory (e.g. by limiting the number of threads that should be used) that SJARACNe uses?

**System Info**

- Arch Linux 4.20.5 (64-bit)
- Python 3.6.8
- Numpy 1.14.2
- argparse 1.1
- igraph 0.7.1
- pandas 0.22.0
- xlsxwriter 1.0.2
- perl 5.28.1

**Comment by adamdingliang** [comment]
Hi khughitt,

Thank you for your interests in SJARACNe and sorry for the delay on reply this. 

1. We benchmarked SJARACNe on a dataset with 28 278 genes x 1000 samples. The memory consumption is about 8G.  You data doubled the number of genes. We think the memory consumption does not increase linearly. We don't have the formula to predict the memory consumption.

2. If you are asking whether there is a way to balance time and memory consumption, unfortunately, we don't know a way to adjust it using the parameters.

We will look more into the questions you asked. Thanks again.

**Comment by adamdingliang** [comment]
Updates: 
we are planning to re-engineer the workflow using CWL, which would allow users to control the number of processes spawned to limit the amount of memory usage.

**Comment by khughitt** [comment]
That's great! One other related issue I noticed, that perhaps could be investigated during the refactoring is that during the step which generates the individual bootstrapped networks (`02-xx`), the processes would sometimes fail without any notice, likely also due to memory issues.

**Comment by adamdingliang** [comment]
We have released 0.2.0. This issue should have been resolved. Thanks for your patience.
