### ISSUE TITLE
Problem finding sjaracne.exe

### ISSUE THREAD

**Issue by albertoriva** [jyyulab/SJARACNe#30]
I installed the program using the conda environment, but when I run it I get the following error:

ERROR 'sjaracne.exe' not found: [Errno 2] No such file or directory: 'sjaracne.exe': 'sjaracne.exe'

This is my command line:

sjaracne local -e ./expressions.txt -g ./hs-tf.txt -o out

Thank you!

**Comment by KGZaker** [comment]
Got the same problem. Could you have solved it yet?

mac osX 10.14.6, python=3.6.1 (conda), numpy>=1.14.2, scipy==1.0.1, pandas==0.22.0, cwltool==1.0.20190618201008

**Comment by adamdingliang** [comment]
Try to install it from source:
$ git clone https://github.com/jyyulab/SJARACNe
$ cd SJARACNe
$ python setup.py build     # build SJARACNe binary
$ python setup.py install

python setup.py build is to build sjaracne.exe binary.
