### ISSUE TITLE
Python version, has to be 3.6.1?

### ISSUE THREAD

**Issue by jasonchian** [jyyulab/SJARACNe#32]
Hi,

Can SJARACne run with a Python version higher than 3.6.1 (3.6.5, for example), or it has to be 3.6.1?

Thanks,

Jason

**Comment by adamdingliang** [comment]
No, it does have to be 3.6.1. We put 3.6.1 because we tested it under 3.6.1 environment. We upgrade python in the newest release SJARACNe 0.2.1 to 3.7.4.
