### ISSUE TITLE
numpy needs more stringency in version

### ISSUE THREAD

**Issue by guillaumecharbonnier** [jyyulab/SJARACNe#34]
The current `requirements.txt` leads to the installation of a numpy version with missing component:
```
ModuleNotFoundError: No module named 'numpy.testing.decorators'
```
Downgrading from the default v1.19.5 to v1.17.5 solved the issue.

**Comment by adamdingliang** [comment]
Thanks for reporting the issue and figuring out a solution.

We have tested release 0.2.1 with numpy==1.20.1. Did not reproduce ModuleNotFoundError.
