### ISSUE TITLE
ERROR Exception while running job

### ISSUE THREAD

**Issue by hyosilpro** [jyyulab/SJARACNe#35]
I got error

i have install  from source
and then run

sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final

but i got the below error
subprocess.CalledProcessError: Command '['cwltool', '--parallel', '--outdir', './test_data/outputs/cwl/cwltool/SJARACNE_out.final',

**Comment by lulugato12** [comment]
@hyosilpro I installed using pip and got the same error.
I ran it in Windows.

Also this: 
raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.exceptions.ValidationException: Not found: 'c:usershpanaconda3envssjaracnelibsite-packagesSJARACNe/cwl/sjaracne_workflow.cwl'

**Comment by lulugato12** [comment]
@hyosilpro
Same error here: https://github.com/jyyulab/SJARACNe/issues/22#issue-537296986

**Comment by hyosilpro** [comment]
> @hyosilpro
> Same error here: [#22 (comment)](https://github.com/jyyulab/SJARACNe/issues/22#issue-537296986)
> It seems that it has to do with Windows 😪

Thank, we have to :(

**Comment by adamdingliang** [comment]
Yes, I already answer this question in #22 . A possible walkaround [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install) was suggested by @j-andrews7 in #22 . Or install a virtual Linux OS under Windows using VMware or Virtual Box.

**Comment by adamdingliang** [comment]
Close this issue. Please reopen if the problem persists. Thanks.
