### ISSUE TITLE
empty output file

### ISSUE THREAD

**Issue by SamTransformer** [jyyulab/SJARACNe#36]
Hi, I ran the test command, everything seems to be fine but the output file (consensus_network_ncol_.txt) is empty (76 bytes). What could be the possible reason?
Also, what is the best way to export an expression matrix from R to be compatible with the input format? I always have to delete double quotes around the strings when using the write.table function. 

(py374) me@MacBook-Pro-2 SJARACNe % sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final
INFO:root:test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO:root:exp_file:
  class: File
  path: /Users/me/Documents/GitHub/tabula-muris-senis/Data/MACA/bulk_data/ARACNe-AP3/GSE_Gene_Folder/SJARACNe/test_data/inputs/BRCA100.exp
probe_file:
  class: File
  path: /Users/me/Documents/GitHub/tabula-muris-senis/Data/MACA/bulk_data/ARACNe-AP3/GSE_Gene_Folder/SJARACNe/test_data/inputs/tf.txt
p_value_consensus: 1e-05
p_value_bootstrap: 1e-07
depth: 40
aracne_config_dir:
  class: Directory
  path: /Users/me/opt/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/config
bootstrap_num: 2
final_out_dir_name: SJARACNE_out.final
INFO:root:cwltool --parallel --outdir ./test_data/outputs/cwl/cwltool/SJARACNE_out.final /Users/me/opt/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO /Users/me/opt/anaconda3/envs/py374/bin/cwltool 3.1.20220119140128
INFO Resolved '/Users/me/opt/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl' to 'file:///Users/me/opt/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl'
INFO [workflow ] starting step create_seeds
INFO [step create_seeds] start
INFO [workflow ] starting step ch_ending_exp
INFO [step ch_ending_exp] start
INFO [workflow ] start
INFO [workflow ] starting step create_adjmat_names
INFO [step create_adjmat_names] start
INFO [workflow ] starting step validate_files
INFO [step validate_files] start
INFO [job ch_ending_exp] /private/tmp/docker_tmp7obqriib$ ch_line_ending.py \
    -i \
    BRCA100.exp
INFO [workflow ] starting step ch_ending_probe
INFO [step ch_ending_probe] start
INFO [job validate_files] /private/tmp/docker_tmpfxaywulf$ QC_input.py \
    -e \
    BRCA100.exp \
    -g \
    tf.txt
INFO [job ch_ending_probe] /private/tmp/docker_tmpcpcd_806$ ch_line_ending.py \
    -i \
    tf.txt
Unix line ending. No need to convert
Unix line ending. No need to convert
INFO [step create_seeds] completed success
INFO [step create_adjmat_names] completed success
INFO [job ch_ending_probe] completed success
INFO [step ch_ending_probe] completed success
INFO [job ch_ending_exp] completed success
INFO [step ch_ending_exp] completed success
INFO [workflow ] starting step bootstrap
INFO [step bootstrap] start
INFO [step bootstrap] start
INFO [job bootstrap] /private/tmp/docker_tmpl81aw14o$ sjaracne.exe \
    -i \
    /private/tmp/docker_tmp15399vo4/stg55dafd91-44c8-4389-8df6-60ac7b1c80b7/BRCA100.exp \
    -l \
    /private/tmp/docker_tmp15399vo4/stg7948ea55-4804-403b-be2d-5fdaced8d6b3/tf.txt \
    -s \
    /private/tmp/docker_tmp15399vo4/stg7948ea55-4804-403b-be2d-5fdaced8d6b3/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /private/tmp/docker_tmp15399vo4/stg0c62de08-8d48-4744-a70a-65a945e3a2d9/config \
    -N \
    40 \
    -o \
    TF_run_001.adj \
    -S \
    1
Displaying parameters

[PARA] Input file:    /private/tmp/docker_tmp15399vo4/stg55dafd91-44c8-4389-8df6-60ac7b1c80b7/BRCA100.exp
[PARA] Output file:   TF_run_001.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
INFO [job bootstrap_2] /private/tmp/docker_tmp5tw8iri3$ sjaracne.exe \
    -i \
    /private/tmp/docker_tmp66scs3v6/stgc6734db1-38c2-47ef-806c-3a703e249c46/BRCA100.exp \
    -l \
    /private/tmp/docker_tmp66scs3v6/stg01828072-9cdb-4d56-91fa-d5aeedf30ba4/tf.txt \
    -s \
    /private/tmp/docker_tmp66scs3v6/stg01828072-9cdb-4d56-91fa-d5aeedf30ba4/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /private/tmp/docker_tmp66scs3v6/stg981983cd-7e89-4a77-adac-0bdc3a5e063a/config \
    -N \
    40 \
    -o \
    TF_run_002.adj \
    -S \
    2
[PARA] Subset of probes to reconstruct: /private/tmp/docker_tmp15399vo4/stg7948ea55-4804-403b-be2d-5fdaced8d6b3/tf.txt (2608)
[PARA] TF annotation list: /private/tmp/docker_tmp15399vo4/stg7948ea55-4804-403b-be2d-5fdaced8d6b3/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
Displaying parameters

[PARA] Input file:    /private/tmp/docker_tmp66scs3v6/stgc6734db1-38c2-47ef-806c-3a703e249c46/BRCA100.exp
[PARA] Output file:   TF_run_002.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
[PARA] Subset of probes to reconstruct: /private/tmp/docker_tmp66scs3v6/stg01828072-9cdb-4d56-91fa-d5aeedf30ba4/tf.txt (2608)
[PARA] TF annotation list: /private/tmp/docker_tmp66scs3v6/stg01828072-9cdb-4d56-91fa-d5aeedf30ba4/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
INFO:root:Number of genes in expression matrix: 28278
INFO:root:Number of hub genes in probe file: 2608
INFO [job validate_files] completed success
INFO [step validate_files] completed success
Marker No: 28278 (28278 active), Array No: 100
MI threshold determined for p=1e-07: 0.153257
Marker No: 28278 (28278 active), Array No: 100
MI threshold determined for p=1e-07: 0.153257
10%, time: 98
10%, time: 104
20%, time: 191
20%, time: 206
30%, time: 289
30%, time: 312
40%, time: 386
40%, time: 417
50%, time: 484
50%, time: 522
60%, time: 584
60%, time: 629
70%, time: 683
70%, time: 737
80%, time: 780
80%, time: 841
90%, time: 876
90%, time: 947
Gene: 2608 Time: 975
[NETWORK] Applying DPI ...
DPI running time is: 22
Writing matrix: TF_run_001.adj
Maximum observed npar: 4
INFO [job bootstrap] Max memory used: 31MiB
INFO [job bootstrap] completed success
Gene: 2608 Time: 1056
[NETWORK] Applying DPI ...
DPI running time is: 72
Writing matrix: TF_run_002.adj
Maximum observed npar: 5
INFO [job bootstrap_2] Max memory used: 43MiB
INFO [job bootstrap_2] completed success
INFO [step bootstrap] completed success
INFO [workflow ] starting step copy_to_dir
INFO [step copy_to_dir] start
INFO [step copy_to_dir] completed success
INFO [workflow ] starting step consensus
INFO [step consensus] start
INFO [job consensus] /private/tmp/docker_tmpbwqqp6k8$ create_consensus_network.py \
    -a \
    /private/tmp/docker_tmps2hu55p1/stg0f32d3cf-d297-49fe-b902-1f2f5071aa95/SJARACNE_out.final \
    -p \
    1e-05 \
    -e \
    /private/tmp/docker_tmps2hu55p1/stgfe88ced8-c78a-4980-849a-0ecc54fe65ec/BRCA100.exp \
    -o \
    SJARACNE_out.final
INFO:root:Create an initial consensus network ...
INFO:root:Done
INFO:root:Create an enhanced consensus network ...
INFO:root:All done
INFO [job consensus] Max memory used: 97MiB
INFO [job consensus] completed success
INFO [step consensus] completed success
INFO [workflow ] completed success
{
    "out_dir": {
        "location": "file:///Users/me/Documents/GitHub/tabula-muris-senis/Data/MACA/bulk_data/ARACNe-AP3/GSE_Gene_Folder/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt",
        "basename": "consensus_network_ncol_.txt",
        "class": "File",
        "checksum": "sha1$823c13f202337831dc1033bc8ced26948e01267a",
        "size": 76,
        "path": "/Users/me/Documents/GitHub/tabula-muris-senis/Data/MACA/bulk_data/ARACNe-AP3/GSE_Gene_Folder/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt"
    }
}
INFO Final process status is success
INFO:root:All done.

**Comment by liu7923** [comment]
I had the same problem. Have you find a way to resolve it? Thanks!

**Comment by SamTransformer** [comment]
No, I have to use the original ARACNe. I’m new to the field 😓

**Comment by adamdingliang** [comment]
For the empty output problem, it is most likely due to gene IDs in the TF or SIG list file do not match with the gene IDs in the input expression file. Also, make sure the format of your input expression matrix file is a tab-separated genes/protein by cells/samples expression matrix with the first two columns being ID and symbol, see test data https://github.com/jyyulab/SJARACNe/blob/master/test_data/inputs/BRCA100.exp for an example.

**Comment by adamdingliang** [comment]
Please reopen this issue if you still have this problem. Thanks.

**Comment by liu7923** [comment]
Thanks for your reply. I actually ran the example command provided in ReadMe file  (sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final). It seems everything is good, but he output file (consensus_network_ncol_.txt) is empty. I double checked the gene IDs in input expression file (BRCA100.exp) and TF list file (tf.txt), and they matched very well. Please let me know if you have any other idea about this problem. Thank you very much!

**Comment by liu7923** [comment]
Thanks for your reply. I actually ran the example command provided in
ReadMe file (sjaracne local -e ./test_data/inputs/BRCA100.exp -g
./test_data/inputs/tf.txt -n 2 -o
./test_data/outputs/cwl/cwltool/SJARACNE_out.final). It seems everything is
good, but the output file (consensus_network_ncol_.txt) is empty. I double
checked the gene IDs in the input expression file (BRCA100.exp) and TF list
file (tf.txt), and they matched very well. Please let me know if you have
any other ideas about this problem. Thank you very much!

Best regards,
Lili
