### ISSUE TITLE
empty output file

### ISSUE THREAD

**Issue by liu7923** [jyyulab/SJARACNe#37]
Hi, I am sorry for bothering you again with the empty output file issue. I really like this method and would like to apply it to my own RNA-seq data.

I actually ran the example command provided in README file (sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final). It seems everything is good, but the output file (consensus_network_ncol_.txt) is empty (please see the details below). I double checked the gene IDs in the input expression file (BRCA100.exp) and TF list file (tf.txt), and they matched very well. Please let me know if you have any suggestions about this problem. Thank you very much!

(py374) SJARACNe $$ sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final
INFO:root:test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO:root:exp_file:
  class: File
  path: /mnt/workspace/lili/software/SJARACNe/test_data/inputs/BRCA100.exp
probe_file:
  class: File
  path: /mnt/workspace/lili/software/SJARACNe/test_data/inputs/tf.txt
p_value_consensus: 1e-05
p_value_bootstrap: 1e-07
depth: 40
aracne_config_dir:
  class: Directory
  path: /mnt/userspace/lili/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/config
bootstrap_num: 2
final_out_dir_name: SJARACNE_out.final
INFO:root:cwltool --parallel --outdir ./test_data/outputs/cwl/cwltool/SJARACNE_out.final /mnt/userspace/lili/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO /mnt/userspace/lili/anaconda3/envs/py374/bin/cwltool 3.1.20211107152837
INFO Resolved '/mnt/userspace/lili/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl' to 'file:///mnt/userspace/lili/anaconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl'
INFO [workflow ] starting step ch_ending_probe
INFO [workflow ] start
INFO [step ch_ending_probe] start
INFO [workflow ] starting step create_seeds
INFO [step create_seeds] start
INFO [workflow ] starting step validate_files
INFO [step validate_files] start
INFO [job ch_ending_probe] /tmp/3lq_6sbq$ ch_line_ending.py \
    -i \
    tf.txt
INFO [workflow ] starting step create_adjmat_names
INFO [step create_adjmat_names] start
INFO [workflow ] starting step ch_ending_exp
INFO [step ch_ending_exp] start
INFO [job ch_ending_exp] /tmp/3bhec4c4$ ch_line_ending.py \
    -i \
    BRCA100.exp
INFO [job validate_files] /tmp/4xxm7r8y$ QC_input.py \
    -e \
    BRCA100.exp \
    -g \
    tf.txt
Unix line ending. No need to convert
Unix line ending. No need to convert
INFO [step create_seeds] completed success
INFO [step create_adjmat_names] completed success
INFO [job ch_ending_probe] completed success
INFO [step ch_ending_probe] completed success
INFO:root:Number of genes in expression matrix: 28278
INFO:root:Number of hub genes in probe file: 2608
INFO [job validate_files] completed success
INFO [step validate_files] completed success
INFO [job ch_ending_exp] completed success
INFO [step ch_ending_exp] completed success
INFO [workflow ] starting step bootstrap
INFO [step bootstrap] start
INFO [step bootstrap] start
INFO [job bootstrap] /tmp/au1hrkx8$ sjaracne.exe \
    -i \
    /tmp/qb0xobu0/stge6207d86-b55f-4ddb-80e5-f991eeb0e874/BRCA100.exp \
    -l \
    /tmp/qb0xobu0/stg8f1e99ca-43ad-4808-aaab-c0d117f38ef5/tf.txt \
    -s \
    /tmp/qb0xobu0/stg8f1e99ca-43ad-4808-aaab-c0d117f38ef5/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /tmp/qb0xobu0/stgc20aecff-67f7-4303-b6f6-aeb34c001364/config \
    -N \
    40 \
    -o \
    TF_run_001.adj \
    -S \
    1
INFO [job bootstrap_2] /tmp/_qy5gmaz$ sjaracne.exe \
    -i \
    /tmp/g5cml312/stg9627380e-0328-4131-91b2-f6638193b937/BRCA100.exp \
    -l \
    /tmp/g5cml312/stg4dc9aae6-3b92-4ee2-abfa-3e9170b388fd/tf.txt \
    -s \
    /tmp/g5cml312/stg4dc9aae6-3b92-4ee2-abfa-3e9170b388fd/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /tmp/g5cml312/stgc0eb7267-672f-4f60-a2b7-2e9bde53387e/config \
    -N \
    40 \
    -o \
    TF_run_002.adj \
    -S \
    2
Displaying parameters

[PARA] Input file:    /tmp/g5cml312/stg9627380e-0328-4131-91b2-f6638193b937/BRCA100.exp
[PARA] Output file:   TF_run_002.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
Displaying parameters

[PARA] Input file:    /tmp/qb0xobu0/stge6207d86-b55f-4ddb-80e5-f991eeb0e874/BRCA100.exp
[PARA] Output file:   TF_run_001.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
[PARA] Subset of probes to reconstruct: /tmp/g5cml312/stg4dc9aae6-3b92-4ee2-abfa-3e9170b388fd/tf.txt (2608)
[PARA] Subset of probes to reconstruct: /tmp/qb0xobu0/stg8f1e99ca-43ad-4808-aaab-c0d117f38ef5/tf.txt (2608)
[PARA] TF annotation list: /tmp/g5cml312/stg4dc9aae6-3b92-4ee2-abfa-3e9170b388fd/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
[PARA] TF annotation list: /tmp/qb0xobu0/stg8f1e99ca-43ad-4808-aaab-c0d117f38ef5/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
Marker No: 28278 (28278 active), Array No: 100
Marker No: 28278 (28278 active), Array No: 100
MI threshold determined for p=1e-07: 0.153257
MI threshold determined for p=1e-07: 0.153257
10%, time: 68
10%, time: 71
20%, time: 134
20%, time: 142
30%, time: 201
30%, time: 213
40%, time: 269
40%, time: 284
50%, time: 336
50%, time: 355
60%, time: 403
60%, time: 426
70%, time: 470
70%, time: 497
80%, time: 537
80%, time: 568
90%, time: 604
90%, time: 639
Gene: 2608 Time: 671
[NETWORK] Applying DPI ...
Gene: 2608 Time: 709
[NETWORK] Applying DPI ...
DPI running time is: 74
Writing matrix: TF_run_002.adj
Maximum observed npar: 4
INFO [job bootstrap_2] Max memory used: 44MiB
INFO [job bootstrap_2] completed success
DPI running time is: 44
Writing matrix: TF_run_001.adj
Maximum observed npar: 4
INFO [job bootstrap] Max memory used: 44MiB
INFO [job bootstrap] completed success
INFO [step bootstrap] completed success
INFO [workflow ] starting step copy_to_dir
INFO [step copy_to_dir] start
INFO [step copy_to_dir] completed success
INFO [workflow ] starting step consensus
INFO [step consensus] start
INFO [job consensus] /tmp/7xvey2xl$ create_consensus_network.py \
    -a \
    /tmp/wkgmm1xk/stgd130b55f-7eed-4ab2-9571-85fd48bee053/SJARACNE_out.final \
    -p \
    1e-05 \
    -e \
    /tmp/wkgmm1xk/stg40ee836d-106d-4342-a870-13cc30a161fe/BRCA100.exp \
    -o \
    SJARACNE_out.final
INFO:root:Create an initial consensus network ...
INFO:root:Done
INFO:root:Create an enhanced consensus network ...
INFO:root:All done
INFO [job consensus] Max memory used: 195MiB
INFO [job consensus] completed success
INFO [step consensus] completed success
INFO [workflow ] completed success
{
    "out_dir": {
        "location": "file:///mnt/workspace/lili/software/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt",
        "basename": "consensus_network_ncol_.txt",
        "class": "File",
        "checksum": "sha1$823c13f202337831dc1033bc8ced26948e01267a",
        "size": 76,
        "path": "/mnt/workspace/lili/software/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt"
    }
}
INFO Final process status is success
INFO:root:All done.

Best,
Lili

**Comment by jonathan-f** [comment]
Hello, I have exactly the same issue.

I have installed a conda environment with python 3.7.4 as suggested with the required packages and I am using SJARACNe version 0.2.1 on a machine with Ubuntu 18.04.5.

Any help would be appreciated.

Thanks
Best
Jonathan

**Comment by garciaaxnih** [comment]
Hi,

I am facing the same issue using the example command as well. Has there been any fix?

Thanks!

**Comment by msc245** [comment]
Hi,

I am facing the same issue using the example command as well. Has there been any fix?

Thanks!

**Comment by saisaitian** [comment]
```
(py374) tss1@bio-PowerEdge-T640:~/SJARACNe$ sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final
INFO:root:test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO:root:exp_file:
  class: File
  path: /home/data/tss1/SJARACNe/test_data/inputs/BRCA100.exp
probe_file:
  class: File
  path: /home/data/tss1/SJARACNe/test_data/inputs/tf.txt
p_value_consensus: 1e-05
p_value_bootstrap: 1e-07
depth: 40
aracne_config_dir:
  class: Directory
  path: /home/data/tss1/miniconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/config
bootstrap_num: 2
final_out_dir_name: SJARACNE_out.final
INFO:root:cwltool --parallel --outdir ./test_data/outputs/cwl/cwltool/SJARACNE_out.final /home/data/tss1/miniconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO /home/data/tss1/miniconda3/envs/py374/bin/cwltool 3.1.20220628170238
INFO Resolved '/home/data/tss1/miniconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl' to 'file:///home/data/tss1/miniconda3/envs/py374/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl'
INFO [workflow ] starting step create_seeds
INFO [workflow ] start
INFO [step create_seeds] start
INFO [workflow ] starting step ch_ending_exp
INFO [step ch_ending_exp] start
INFO [workflow ] starting step validate_files
INFO [step validate_files] start
INFO [job ch_ending_exp] /tmp/0e_sr7bh$ ch_line_ending.py \
    -i \
    BRCA100.exp
INFO [workflow ] starting step create_adjmat_names
INFO [step create_adjmat_names] start
INFO [workflow ] starting step ch_ending_probe
INFO [step ch_ending_probe] start
INFO [job validate_files] /tmp/kmyzrqw2$ QC_input.py \
    -e \
    BRCA100.exp \
    -g \
    tf.txt
INFO [job ch_ending_probe] /tmp/oipyo3d8$ ch_line_ending.py \
    -i \
    tf.txt
Unix line ending. No need to convert
Unix line ending. No need to convert
INFO [step create_seeds] completed success
INFO [step create_adjmat_names] completed success
INFO:root:Number of genes in expression matrix: 28278
INFO:root:Number of hub genes in probe file: 2608
INFO [job validate_files] completed success
INFO [step validate_files] completed success
INFO [job ch_ending_probe] completed success
INFO [step ch_ending_probe] completed success
INFO [job ch_ending_exp] completed success
INFO [step ch_ending_exp] completed success
INFO [workflow ] starting step bootstrap
INFO [step bootstrap] start
INFO [step bootstrap] start
INFO [job bootstrap] /tmp/qf8jjsob$ sjaracne.exe \
    -i \
    /tmp/iir2p7yd/stg66198979-8e36-4f70-980f-938606ad3f9a/BRCA100.exp \
    -l \
    /tmp/iir2p7yd/stga64eaf23-7b38-43a0-afbf-b95e9470b280/tf.txt \
    -s \
    /tmp/iir2p7yd/stga64eaf23-7b38-43a0-afbf-b95e9470b280/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /tmp/iir2p7yd/stg5eb30709-f4f8-48a5-b1f7-c4b9babd3122/config \
    -N \
    40 \
    -o \
    TF_run_001.adj \
    -S \
    1
INFO [job bootstrap_2] /tmp/lv_msu1l$ sjaracne.exe \
    -i \
    /tmp/cw7agx5q/stgcaa94e5a-9067-4605-85ff-117c848bdaa5/BRCA100.exp \
    -l \
    /tmp/cw7agx5q/stgf0e92bbc-7a85-4fbf-8cfe-83b7b053cb11/tf.txt \
    -s \
    /tmp/cw7agx5q/stgf0e92bbc-7a85-4fbf-8cfe-83b7b053cb11/tf.txt \
    -p \
    1e-07 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /tmp/cw7agx5q/stgfc66403d-66eb-4ce4-a2d7-2b7aac8a701e/config \
    -N \
    40 \
    -o \
    TF_run_002.adj \
    -S \
    2
Displaying parameters

[PARA] Input file:    /tmp/iir2p7yd/stg66198979-8e36-4f70-980f-938606ad3f9a/BRCA100.exp
[PARA] Output file:   TF_run_001.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
[PARA] Subset of probes to reconstruct: /tmp/iir2p7yd/stga64eaf23-7b38-43a0-afbf-b95e9470b280/tf.txt (2608)
[PARA] TF annotation list: /tmp/iir2p7yd/stga64eaf23-7b38-43a0-afbf-b95e9470b280/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
Displaying parameters

[PARA] Input file:    /tmp/cw7agx5q/stgcaa94e5a-9067-4605-85ff-117c848bdaa5/BRCA100.exp
[PARA] Output file:   TF_run_002.adj
[PARA] MI P-value:    1e-07
[PARA] DPI tolerance: 0
[PARA] Subset of probes to reconstruct: /tmp/cw7agx5q/stgf0e92bbc-7a85-4fbf-8cfe-83b7b053cb11/tf.txt (2608)
[PARA] TF annotation list: /tmp/cw7agx5q/stgf0e92bbc-7a85-4fbf-8cfe-83b7b053cb11/tf.txt (2608)
[PARA] Npar limit:    40

[READ] 0 Description lines bypassed.
[READ] P-value columns not found.
Marker No: 28278 (28278 active), Array No: 100
MI threshold determined for p=1e-07: 0.153257
Marker No: 28278 (28278 active), Array No: 100
MI threshold determined for p=1e-07: 0.153257
10%, time: 82
10%, time: 84
20%, time: 166
20%, time: 166
30%, time: 247
30%, time: 248
40%, time: 331
40%, time: 332
50%, time: 416
50%, time: 418
60%, time: 495
60%, time: 497
70%, time: 576
70%, time: 578
80%, time: 658
80%, time: 661
90%, time: 740
90%, time: 742
Gene: 2608 Time: 821
[NETWORK] Applying DPI ...
Gene: 2608 Time: 823
[NETWORK] Applying DPI ...
DPI running time is: 46
Writing matrix: TF_run_001.adj
Maximum observed npar: 4
INFO [job bootstrap] Max memory used: 54MiB
INFO [job bootstrap] completed success
DPI running time is: 79
Writing matrix: TF_run_002.adj
Maximum observed npar: 4
INFO [job bootstrap_2] Max memory used: 55MiB
INFO [job bootstrap_2] completed success
INFO [step bootstrap] completed success
INFO [workflow ] starting step copy_to_dir
INFO [step copy_to_dir] start
INFO [step copy_to_dir] completed success
INFO [workflow ] starting step consensus
INFO [step consensus] start
INFO [job consensus] /tmp/dbtk7o0i$ create_consensus_network.py \
    -a \
    /tmp/7ww6dysz/stg20fe3d99-ccf9-49f1-955d-0d27a93baf70/SJARACNE_out.final \
    -p \
    1e-05 \
    -e \
    /tmp/7ww6dysz/stgc3268edc-efad-45da-8ead-06c98be5326b/BRCA100.exp \
    -o \
    SJARACNE_out.final
INFO:root:Create an initial consensus network ...
INFO:root:Done
INFO:root:Create an enhanced consensus network ...
INFO:root:All done
INFO [job consensus] Max memory used: 192MiB
INFO [job consensus] completed success
INFO [step consensus] completed success
INFO [workflow ] completed success
{
    "out_dir": {
        "location": "file:///home/data/tss1/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt",
        "basename": "consensus_network_ncol_.txt",
        "class": "File",
        "checksum": "sha1$823c13f202337831dc1033bc8ced26948e01267a",
        "size": 76,
        "path": "/home/data/tss1/SJARACNe/test_data/outputs/cwl/cwltool/SJARACNE_out.final/consensus_network_ncol_.txt"
    }
}
INFO Final process status is success
INFO:root:All done.
```
everything is ok，but the output is empty! could you tell me how to solve it?

![image](https://user-images.githubusercontent.com/26356557/178105984-56f1c593-71ec-427e-8d0f-290c7720e296.png)
![image](https://user-images.githubusercontent.com/26356557/178105996-382353d2-e9dd-484f-b3bc-4d3adb79664c.png)

**Comment by adamdingliang** [comment]
See issue #39.
