### ISSUE TITLE
i can't assign a path for my tmp file

### ISSUE THREAD

**Issue by li1311139481** [jyyulab/SJARACNe#42]
I run SJARACNe on the computer cluster.

I use slurm to request a compute node and then run my command.

`#!/bin/bash
#SBATCH -J zf020.MP.TE.8.highmem              ######作业名
#SBATCH -o /public/home/zifeng/eo/%j.%x.out         ######输出文件重定向
#SBATCH -e /public/home/zifeng/eo/%j.%x.err         ######报错文件重定向
#SBATCH -p high_mem      
#SBATCH --qos=low
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH -A huanghlgroup
#################################

for i in $*
do
  sjaracne local -e $i/input.exp -g $i/sig.txt -o $i/output_sig_sjaracne_network_out_.final
  sjaracne local -e $i/input.exp -g $i/tf.txt -o $i/output_tf_sjaracne_network_out_.final
done`

i get a error like this 

![图片](https://user-images.githubusercontent.com/109973822/208581624-df176b4a-7044-488b-a8bd-635fb2521e46.png)

I have 2T of memory.  So I don't think it's a memory problem. And I noticed that on a new compute node, I could get the output of SJARACNe. but if I run SJARACNe multiple times on the node, I will get the error, or no error but also no output

The computer cluster administrator tells me that **I need to specify /tmp path because he found that the /tmp path for the compute node is full.** So I want to know how to specify this directory

**Comment by li1311139481** [comment]
I noticed that #18 mentioned this problem. Has it been solved now？

**Comment by li1311139481** [comment]
anyone can help me? please

**Comment by leiyan** [comment]
Hi @li1311139481 , some comments:

"No space left on device" ---- this issue usually refers to hard disk space, not memory.

If you can, you can set a virtual path (/tmp) pointing to a big enough space or directory.
FYI, you can use "Bind Mount":
https://www.baeldung.com/linux/bind-mounts

Our team will work on the "specify temp dir".

**Comment by li1311139481** [comment]
Thanks for your reply @leiyan . Here is my reply:
I consulted the computer cluster administrator and he told me that only the root user can run `mount --bind` . 
and `mount --bind` usually only used as a test to test a code. So, I think I have to wait your work on `specify temp dir`. 
I really appreciate for your reply.

**Comment by leiyan** [comment]
Added parameter tmpdir-prefix for cwltool:

https://github.com/jyyulab/SJARACNe/commit/78f878664443e0a2c65ae090c77758b948067e8a
