### ISSUE TITLE
 Did not find output file with glob pattern: ['TF_run_001.adj'].", {}

### ISSUE THREAD

**Issue by luochx5** [jyyulab/SJARACNe#44]
Hi,

I installed the 'Prerequisites' packages and installed SJARACNE 0.2.1 via 'Option 2 install from source'. 
But I'm having trouble getting SJARACNe to do [job bootstrap]. 

 sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final -pc 1.0 -tmp ./test_data/outputs/cwl/cwltool/tmp/
INFO:root:test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO:root:exp_file:
  class: File
  path: /home/luochenx/SJARACNe/test_data/inputs/BRCA100.exp
probe_file:
  class: File
  path: /home/luochenx/SJARACNe/test_data/inputs/tf.txt
p_value_consensus: 1.0
p_value_bootstrap: 1e-07
depth: 40
aracne_config_dir:
  class: Directory
  path: /home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/config
bootstrap_num: 2
final_out_dir_name: SJARACNE_out.final
INFO:root:cwltool --tmpdir-prefix ./test_data/outputs/cwl/cwltool/tmp/ --parallel --outdir ./test_data/outputs/cwl/cwltool/SJARACNE_out.final /home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml
INFO /home/luochenx/miniconda3/envs/py376/bin/cwltool 3.1.20230719185429
INFO Resolved '/home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl' to 'file:///home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl'
INFO [workflow ] starting step create_seeds
INFO [workflow ] start
INFO [step create_seeds] start
INFO [workflow ] starting step ch_ending_probe
INFO [step ch_ending_probe] start
INFO [workflow ] starting step validate_files
INFO [step validate_files] start
INFO [job ch_ending_probe] /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/xve_t_er$ ch_line_ending.py \
    -i \
    tf.txt
INFO [workflow ] starting step ch_ending_exp
INFO [step ch_ending_exp] start
INFO [job validate_files] /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/jfy4h0bl$ QC_input.py \
    -e \
    BRCA100.exp \
    -g \
    tf.txt
INFO [workflow ] starting step create_adjmat_names
INFO [step create_adjmat_names] start
INFO [job ch_ending_exp] /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/n1gfgwfc$ ch_line_ending.py \
    -i \
    BRCA100.exp
Unix line ending. No need to convert
Unix line ending. No need to convert
INFO [step create_seeds] completed success
INFO [step create_adjmat_names] completed success
INFO [job ch_ending_probe] completed success
INFO [step ch_ending_probe] completed success
INFO [job ch_ending_exp] completed success
INFO [step ch_ending_exp] completed success
INFO [workflow ] starting step bootstrap
INFO [step bootstrap] start
INFO [step bootstrap] start
INFO [job bootstrap] /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/utoj2h5j$ sjaracne.exe \
    -i \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/nuac2vxk/stg9302ce80-4b0b-49b8-bb12-39a8cf102ab8/BRCA100.exp \
    -l \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/nuac2vxk/stgba754226-67d7-4884-8f60-e8dc31feccb7/tf.txt \
    -s \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/nuac2vxk/stgba754226-67d7-4884-8f60-e8dc31feccb7/tf.txt \
    -p \
    0 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/nuac2vxk/stg706c63f2-c71f-488d-8011-3c413eee21e0/config \
    -N \
    40 \
    -o \
    TF_run_001.adj \
    -S \
    1
INFO [job bootstrap_2] /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/56oemvqq$ sjaracne.exe \
    -i \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/_r69ayjb/stgc689dc07-b301-49c5-80bc-971f503c94d4/BRCA100.exp \
    -l \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/_r69ayjb/stg22b7ea29-6ec3-455e-919c-8fc6cec32348/tf.txt \
    -s \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/_r69ayjb/stg22b7ea29-6ec3-455e-919c-8fc6cec32348/tf.txt \
    -p \
    0 \
    -e \
    0 \
    -a \
    adaptive_partitioning \
    -r \
    1 \
    -H \
    /home/luochenx/SJARACNe/test_data/outputs/cwl/cwltool/tmp/_r69ayjb/stga683f34d-5ac5-4e5c-a699-c1119726257e/config \
    -N \
    40 \
    -o \
    TF_run_002.adj \
    -S \
    2
sjaracne.exesjaracne.exe: : P-value '-p' must be in the range (0,1]!P-value '-p' must be in the range (0,1]!

**WARNING [job bootstrap] exited with status: 1
WARNING [job bootstrap_2] exited with status: 1**
**ERROR [job bootstrap] Job error:
("Error collecting output for parameter 'out_adj': ../miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne.cwl:85:7: Did not find output file with glob pattern: ['TF_run_001.adj'].", {})
ERROR [job bootstrap_2] Job error:
("Error collecting output for parameter 'out_adj': ../miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne.cwl:85:7: Did not find output file with glob pattern: ['TF_run_002.adj'].", {})
WARNING [job bootstrap] completed permanentFail
WARNING [job bootstrap_2] completed permanentFail
WARNING [step bootstrap] completed permanentFail**
INFO [workflow ] completed permanentFail
INFO:root:Number of genes in expression matrix: 28278
INFO:root:Number of hub genes in probe file: 2608
INFO [job validate_files] completed success
INFO [step validate_files] completed success
{
    "out_dir": null
}WARNING Final process status is permanentFail
Traceback (most recent call last):
  File "/home/luochenx/miniconda3/envs/py376/bin/sjaracne", line 33, in <module>
    sys.exit(load_entry_point('SJARACNe==0.2.1', 'console_scripts', 'sjaracne')())
  File "/home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/sjaracne.py", line 102, in main
    run_shell_command_call(cmd)
  File "/home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/sjaracne.py", line 113, in run_shell_command_call
    subprocess.check_call(cmd_to_exec)
  File "/home/luochenx/miniconda3/envs/py376/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cwltool', '--tmpdir-prefix', './test_data/outputs/cwl/cwltool/tmp/', '--parallel', '--outdir', './test_data/outputs/cwl/cwltool/SJARACNE_out.final', '/home/luochenx/miniconda3/envs/py376/lib/python3.7/site-packages/SJARACNe-0.2.1-py3.7.egg/SJARACNe/cwl/sjaracne_workflow.cwl', 'test_data/outputs/cwl/cwltool/SJARACNE_out.final/sjaracne_workflow.yml']' returned non-zero exit status 1.

Can you please give me some instructions? I have no idea about this error and fail to search for similar issues and solutions.
And when can we have a docker version? I'm looking forward to it!^_^

**Comment by leiyan** [comment]
We have discussed, reinstalled on Windows Subsystem for Linux (WSL), and then installed successfully, running successfully.

![8d9837a4421c77048db30f092b8b728](https://github.com/jyyulab/SJARACNe/assets/1719788/7eec8421-b59b-4ffc-a418-af9d5fb983d4)

Additionally this may be required:
`curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&sudo apt-get install -y nodejs`
