### ISSUE TITLE
This is a successful case of installing the current version of SJARACNe on ubuntu

### ISSUE THREAD

**Issue by leiyan** [jyyulab/SJARACNe#45]
12/8/2023

**Comment by leiyan** [comment]
conda create -n SJARACNe2.1 python=3.7.6

conda activate SJARACNe2.1

#The installation of scipy and numpy cannot be reversed. Scipy will install other versions of numpy by default.
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple scipy==1.6.1
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy==1.20.1
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==1.2.3

#The document requirement is cwltool=>3.0.20201117141248; but only cwltool==3.0.20201117141248 can be installed, and the default installation dependencies cannot be used.
#Be sure to install setuptools==57.5.0 before installing cwltool==3.0.20201117141248, otherwise a dependency error will be reported.
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple setuptools==57.5.0
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple cwltool==3.0.20201117141248

conda install nodejs

conda install git

git clone https://github.com/jyyulab/SJARACNe

cd SJARACNe/

python setup.py build     # build SJARACNe binary
python setup.py install

#The installation is complete.

#To search, give executable permissions to these scripts, otherwise, an error will be reported.
#find xxx -name "ch_line_ending*" -exec chmod +x {} \;
#find xxx -name "QC_input*" -exec chmod +x {} \;
#find xxx -name "create_consensus_network*" -exec chmod +x {} \;

#test run
sjaracne local -e ./test_data/inputs/BRCA100.exp -g ./test_data/inputs/tf.txt -n 2 -o ./test_data/outputs/cwl/cwltool/SJARACNE_out.final -pc 1.0 -tmp ./test_data/outputs/cwl/cwltool/tmp/

**Comment by FWYX** [comment]
牛逼

**Comment by c7cc5** [comment]
Really helped!!!!!!!!!!!!! Thanks for sharing!!!!!!!!

**Comment by c7cc5** [comment]
It works!!!!! Thanks for sharing!!!!!!
